/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
import * as generated from "./../../../../../../../src/lib/schemas/supabase-generated";
export type PublicCommentStatus = z.infer<
  typeof generated.publicCommentStatusSchema
>;
export type PublicPostStatus = z.infer<typeof generated.publicPostStatusSchema>;
export type PublicPostType = z.infer<typeof generated.publicPostTypeSchema>;
export type PublicReactionTarget = z.infer<
  typeof generated.publicReactionTargetSchema
>;
export type PublicReactionType = z.infer<
  typeof generated.publicReactionTypeSchema
>;
export type PublicUserRole = z.infer<typeof generated.publicUserRoleSchema>;
export type Json = z.infer<typeof generated.jsonSchema>;
export type PublicCategoriesRow = z.infer<
  typeof generated.publicCategoriesRowSchema
>;
export type PublicCategoriesInsert = z.infer<
  typeof generated.publicCategoriesInsertSchema
>;
export type PublicCategoriesUpdate = z.infer<
  typeof generated.publicCategoriesUpdateSchema
>;
export type PublicCollectionItemsRow = z.infer<
  typeof generated.publicCollectionItemsRowSchema
>;
export type PublicCollectionItemsInsert = z.infer<
  typeof generated.publicCollectionItemsInsertSchema
>;
export type PublicCollectionItemsUpdate = z.infer<
  typeof generated.publicCollectionItemsUpdateSchema
>;
export type PublicCollectionItemsRelationships = z.infer<
  typeof generated.publicCollectionItemsRelationshipsSchema
>;
export type PublicCollectionsRow = z.infer<
  typeof generated.publicCollectionsRowSchema
>;
export type PublicCollectionsInsert = z.infer<
  typeof generated.publicCollectionsInsertSchema
>;
export type PublicCollectionsUpdate = z.infer<
  typeof generated.publicCollectionsUpdateSchema
>;
export type PublicCollectionsRelationships = z.infer<
  typeof generated.publicCollectionsRelationshipsSchema
>;
export type PublicCommentsRow = z.infer<
  typeof generated.publicCommentsRowSchema
>;
export type PublicCommentsInsert = z.infer<
  typeof generated.publicCommentsInsertSchema
>;
export type PublicCommentsUpdate = z.infer<
  typeof generated.publicCommentsUpdateSchema
>;
export type PublicCommentsRelationships = z.infer<
  typeof generated.publicCommentsRelationshipsSchema
>;
export type PublicFollowsRow = z.infer<typeof generated.publicFollowsRowSchema>;
export type PublicFollowsInsert = z.infer<
  typeof generated.publicFollowsInsertSchema
>;
export type PublicFollowsUpdate = z.infer<
  typeof generated.publicFollowsUpdateSchema
>;
export type PublicFollowsRelationships = z.infer<
  typeof generated.publicFollowsRelationshipsSchema
>;
export type PublicMessagesRow = z.infer<
  typeof generated.publicMessagesRowSchema
>;
export type PublicMessagesInsert = z.infer<
  typeof generated.publicMessagesInsertSchema
>;
export type PublicMessagesUpdate = z.infer<
  typeof generated.publicMessagesUpdateSchema
>;
export type PublicNotificationsRow = z.infer<
  typeof generated.publicNotificationsRowSchema
>;
export type PublicNotificationsInsert = z.infer<
  typeof generated.publicNotificationsInsertSchema
>;
export type PublicNotificationsUpdate = z.infer<
  typeof generated.publicNotificationsUpdateSchema
>;
export type PublicNotificationsRelationships = z.infer<
  typeof generated.publicNotificationsRelationshipsSchema
>;
export type PublicPostTagsRow = z.infer<
  typeof generated.publicPostTagsRowSchema
>;
export type PublicPostTagsInsert = z.infer<
  typeof generated.publicPostTagsInsertSchema
>;
export type PublicPostTagsUpdate = z.infer<
  typeof generated.publicPostTagsUpdateSchema
>;
export type PublicPostTagsRelationships = z.infer<
  typeof generated.publicPostTagsRelationshipsSchema
>;
export type PublicPostTopicsRow = z.infer<
  typeof generated.publicPostTopicsRowSchema
>;
export type PublicPostTopicsInsert = z.infer<
  typeof generated.publicPostTopicsInsertSchema
>;
export type PublicPostTopicsUpdate = z.infer<
  typeof generated.publicPostTopicsUpdateSchema
>;
export type PublicPostTopicsRelationships = z.infer<
  typeof generated.publicPostTopicsRelationshipsSchema
>;
export type PublicPostsRow = z.infer<typeof generated.publicPostsRowSchema>;
export type PublicPostsInsert = z.infer<
  typeof generated.publicPostsInsertSchema
>;
export type PublicPostsUpdate = z.infer<
  typeof generated.publicPostsUpdateSchema
>;
export type PublicPostsRelationships = z.infer<
  typeof generated.publicPostsRelationshipsSchema
>;
export type PublicProfilesRow = z.infer<
  typeof generated.publicProfilesRowSchema
>;
export type PublicProfilesInsert = z.infer<
  typeof generated.publicProfilesInsertSchema
>;
export type PublicProfilesUpdate = z.infer<
  typeof generated.publicProfilesUpdateSchema
>;
export type PublicProfilesRelationships = z.infer<
  typeof generated.publicProfilesRelationshipsSchema
>;
export type PublicReactionsRow = z.infer<
  typeof generated.publicReactionsRowSchema
>;
export type PublicReactionsInsert = z.infer<
  typeof generated.publicReactionsInsertSchema
>;
export type PublicReactionsUpdate = z.infer<
  typeof generated.publicReactionsUpdateSchema
>;
export type PublicReactionsRelationships = z.infer<
  typeof generated.publicReactionsRelationshipsSchema
>;
export type PublicReportsRow = z.infer<typeof generated.publicReportsRowSchema>;
export type PublicReportsInsert = z.infer<
  typeof generated.publicReportsInsertSchema
>;
export type PublicReportsUpdate = z.infer<
  typeof generated.publicReportsUpdateSchema
>;
export type PublicReportsRelationships = z.infer<
  typeof generated.publicReportsRelationshipsSchema
>;
export type PublicTagsRow = z.infer<typeof generated.publicTagsRowSchema>;
export type PublicTagsInsert = z.infer<typeof generated.publicTagsInsertSchema>;
export type PublicTagsUpdate = z.infer<typeof generated.publicTagsUpdateSchema>;
export type PublicTopicsRow = z.infer<typeof generated.publicTopicsRowSchema>;
export type PublicTopicsInsert = z.infer<
  typeof generated.publicTopicsInsertSchema
>;
export type PublicTopicsUpdate = z.infer<
  typeof generated.publicTopicsUpdateSchema
>;
export type PublicTopicsRelationships = z.infer<
  typeof generated.publicTopicsRelationshipsSchema
>;
export type PublicMakeAdminArgs = z.infer<
  typeof generated.publicMakeAdminArgsSchema
>;
export type PublicMakeAdminReturns = z.infer<
  typeof generated.publicMakeAdminReturnsSchema
>;
